### ISSUE TITLE
base level Key's don't get picked up in the config files

### ISSUE THREAD

**Issue by jvsteiner** [joosep-wm/pungi#3]
If I have:
```toml
[testapp]
port = 4444
dbUri = "inmemory"
cpuprofile = true

[testapp.httpgw]
port = 6666
grpcUri = "http://my.friend:5432"
```
no value is read in for `cpuprofile`
